return {
	HaveDoneSave = true,
	BgmOn = true,
	AllowExecute = false,
	ScreenWidth = 1920,
	FullScreen = true,
	ScreenHeight = 1080,
	SeVolume = 100,
	LastEnterWorldIndex = 0,
	SkipTutorialChapters = true,
	BgmVolume = 100,
	MaxScreenWidth = 1920,
	CompletedChapters = 0,
	MonitorIndex = 0,
	Language = "zh-CN",
	HideTaiwuOriginalSurname = true,
	ArchiveFilesBackupInterval = 1,
	ArchiveFilesBackupOn = true,
	SeOn = true,
	MaxScreenHeight = 1080
}